flags: {}
extra-package-dbs: []
packages:
- gelatin-core
- gelatin-gl
#- gelatin-glfw
- gelatin-picture
- gelatin-sdl2
extra-deps:
- linear-1.20.4
- base-orphans-0.5.1
- renderable-0.1.0.0
- vector-0.11.0.0
- sdl2-2.1.1

resolver: lts-3.17
