flags: {}
extra-package-dbs: []
packages:
- '.'
- '../gelatin-core'
- '../gelatin-picture'
- location:
    git: https://github.com/schell/renderable.git
    commit: d1a0b6bcb5412f93cba7188dd45b09420de8e2af
- location:
    git: https://github.com/schell/FontyFruity
    commit: 99c143ebb569c286aa5252587923f8c34423e969
extra-deps: []
resolver: lts-5.2
