flags: {}
extra-package-dbs: []
packages:
- '.'
- '../gelatin-core'
- '../gelatin-picture'
- '../gelatin-gl'
- location:
    git: https://github.com/schell/sdl2.git
    commit: b3e8c9cb707ca45cf443b5103c5fd6dff1bb1fd3
- location:
    git: https://github.com/schell/renderable.git
    commit: 242b09b9a14936f013baf816a7ddd9ae75e0e53b
- location:
    git: https://github.com/schell/FontyFruity
    commit: 99c143ebb569c286aa5252587923f8c34423e969
#extra-deps:
#- sdl2-2.1.1
resolver: lts-5.2
