flags: {}
extra-package-dbs: []
packages: 
- '.'
- '../gelatin-core'
- '../gelatin-picture'
- '../gelatin-gl'
- '../../sdl2'
- location:
    git: https://github.com/schell/renderable.git
    commit: 743ea68c91daeb4c3000f3c0ce2c73fbac02cacc
- location:
    git: https://github.com/schell/FontyFruity
    commit: 99c143ebb569c286aa5252587923f8c34423e969
#extra-deps:
#- sdl2-2.1.1
resolver: lts-5.2
